name: CI Pipeline

on:
  push:
    branches:
      - dev
      - qa
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run linter
      run: flake8 .

    - name: Run tests
      run: pytest

    - name: Run Database Migrations
      env:
        FLASK_APP: ${{ env.FLASK_APP || 'ourapp.py' }} # Ensure FLASK_APP is set
        # Set other necessary environment variables here
      run: |
        export FLASK_APP=ourapp # replace 'ourapp' with the entry point of our Flask application
        flask db upgrade
